"""
OAuth 2.1 protection for the remote MCP server, backed by Microsoft Entra ID.

The MCP server is a RESOURCE SERVER: it never logs anyone in and never issues a
token. It only verifies tokens that Entra issued, which is why swapping identity
providers later means changing this file and nothing else.

The flow (MCP spec 2025-06-18+):

  1. client calls /mcp with no token
  2. server -> 401 + WWW-Authenticate: Bearer resource_metadata="<url>"
  3. client GETs /.well-known/oauth-protected-resource   (RFC 9728, mandatory)
  4. that document names Entra as the authorization server
  5. client does auth-code + PKCE against Entra and gets a token
  6. client retries with Authorization: Bearer <token>
  7. verify_token() below checks it

Validation is deliberately strict about the AUDIENCE. A token minted for some
other API in the same tenant is a perfectly valid Entra token — accepting it
would let any app in the directory call these tools. The audience check is what
makes the token specific to this server.
"""
import os
import time

import httpx
from mcp.server.auth.provider import AccessToken, TokenVerifier

TENANT_ID = os.getenv("ENTRA_TENANT_ID", "")
API_APP_ID = os.getenv("ENTRA_API_APP_ID", "")

# Entra issues v2.0 tokens whose audience is the app id (or api://<app id>).
# Accept both spellings rather than guessing which one the client requested.
VALID_AUDIENCES = {API_APP_ID, f"api://{API_APP_ID}"} if API_APP_ID else set()
ISSUERS = {
    f"https://login.microsoftonline.com/{TENANT_ID}/v2.0",
    f"https://sts.windows.net/{TENANT_ID}/",
}
JWKS_URL = f"https://login.microsoftonline.com/{TENANT_ID}/discovery/v2.0/keys"


def auth_enabled() -> bool:
    """Auth is opt-in: without both ids configured the server stays open, so a
    missing env var can never silently half-protect it.

    (The RFC 9728 metadata document itself is generated by the MCP SDK from
    AuthSettings.resource_server_url — we do not hand-roll it.)"""
    return bool(TENANT_ID and API_APP_ID)


class _JwksCache:
    """Entra's signing keys, cached. Fetching them per request would add a
    round trip to every call and hammer a shared endpoint; they rotate rarely,
    so an hour is a safe TTL. A cache miss on an unknown kid forces a refetch,
    which is what makes key rotation self-healing."""

    def __init__(self, ttl: int = 3600):
        self._keys: dict = {}
        self._fetched_at = 0.0
        self._ttl = ttl

    def get(self, kid: str, force: bool = False):
        if force or not self._keys or time.time() - self._fetched_at > self._ttl:
            resp = httpx.get(JWKS_URL, timeout=20)
            resp.raise_for_status()
            self._keys = {k["kid"]: k for k in resp.json().get("keys", [])}
            self._fetched_at = time.time()
        key = self._keys.get(kid)
        if key is None and not force:
            return self.get(kid, force=True)   # unknown kid -> keys may have rotated
        return key


_jwks = _JwksCache()


class EntraTokenVerifier(TokenVerifier):
    """Verifies an Entra-issued JWT. Returns None on any failure, which the SDK
    turns into a 401 — never raise, or a malformed token becomes a 500."""

    async def verify_token(self, token: str) -> AccessToken | None:
        try:
            from jose import jwt
            from jose.utils import base64url_decode  # noqa: F401  (import check)

            header = jwt.get_unverified_header(token)
            key = _jwks.get(header.get("kid", ""))
            if key is None:
                return None

            # Verify signature and expiry here, but NOT the audience: jose's
            # audience check compares with `audience not in audience_claims`,
            # which only works for a single string. Passing our two accepted
            # spellings as a list would reject every token. So we check the
            # audience ourselves, immediately below — it is the most important
            # claim and must not be skipped.
            claims = jwt.decode(
                token,
                key,
                algorithms=["RS256"],
                options={"verify_aud": False, "verify_exp": True, "verify_signature": True},
            )

            aud = claims.get("aud")
            aud_set = {aud} if isinstance(aud, str) else set(aud or [])
            if not (aud_set & VALID_AUDIENCES):
                return None          # token was minted for a different API

            if claims.get("iss") not in ISSUERS:
                return None

            scopes = (claims.get("scp") or "").split()
            return AccessToken(
                token=token,
                client_id=claims.get("azp") or claims.get("appid") or "unknown",
                scopes=scopes,
                expires_at=claims.get("exp"),
                subject=claims.get("oid") or claims.get("sub"),
                claims=claims,
            )
        except Exception:
            # bad signature, expired, wrong audience, malformed — all just "no"
            return None
